name: AutoPR

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  autopr:
    runs-on: ubuntu-latest
    if: (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/autopr')) || (github.event_name == 'pull_request')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Run AutoPR
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run python -m autopr.gh_actions_entrypoint

      - name: Upload Run Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autopr-run-log-for-paper
          path: .autopr/logs/autopr_run.log